name: 180-days-challenge-2022-frontend
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          TOKEN_HEADER_NAME: '${{ secrets.TOKEN_HEADER_NAME }}'
        run: |
          cd app
          npm ci
          npm run build
          mv docs ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs

